# Generated by Django 5.0.6 on 2024-07-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_friend_user1_alter_friend_user2'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set(),
        ),
    ]
