# Generated by Django 5.0.6 on 2024-07-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_friend_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
