# Generated by Django 5.0.6 on 2024-07-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_hash',
            new_name='password',
        ),
    ]
