# Generated by Django 5.0.6 on 2024-07-04 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_password_hash_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatting_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatting_with', to='main.user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to='main.user')),
            ],
        ),
    ]
